version: '3.7'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seeddb
    ports:
      - "5433:5432"
    volumes:
      - seed_pgdata:/var/lib/postgresql/data
volumes:
  seed_pgdata: